export const QuestionPaperData = [
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
    {
        degree: "Bcom",
        stram: "Computer Application",
        semester: "6",
        qp: "BCMCAV 353",
        examyear: "September 2022",
        paper: "Software Engineering",
        totoalMarks: 80,
        pdfLink: "https://mangaloreuniversity.ac.in/upload/E-Governance/Old-Question-Paper/B.Com/BCMCAV%20353.pdf",
        pdfCover: "",
        type: "qp",
    },
];